#pull base image
FROM alpine:3.6

RUN apk add --no-cache ca-certificates

ARG tag
ENV IMAGE_TAG=$tag

RUN echo "image tag: $IMAGE_TAG"
#ENTRYPOINT "echo ${IMAGE_TAG}"
ENTRYPOINT ["/bin/sh", "-c", "echo $IMAGE_TAG"]

#run
#docker build --no-cache -f ./Dockerfile_arg -t docker.io/interma/demo:${HAWQ_DOCKER_TAG} --build-arg tag=$HAWQ_DOCKER_TAG ./
#docker run interma/demo:arg
